added documentation on how to update the documentation
intelligent-soft-robots/pam_documentation pull request #8
Opened 2021-10-05 13:39 UTC by vincentberenz

[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description

I added a doc on how to update the doc

2021-10-05 14:36 UTC, luator requested changes
Maybe add a point that once can build locally by simply running `make html`.  Only dependencies are sphinx and the stuff listed in requirements.txt.

2021-10-05 14:36 UTC, luator commented on E5_documentation.md
> +- If you add a new file: in the content list, the orders of the page is alphabetical. Name your new markdown file based on the order into which it should appear in the content list.
This is not the case anymore, there is now an `index.rst` that needs to be maintained manually.

2021-10-05 14:36 UTC, luator commented on E5_documentation.md
> +- If you add a new file: in the content list, the orders of the page is alphabetical. Name your new markdown file based on the order into which it should appear in the content list.
I would also suggest to use RST for new files, as I think it is better suited for larger documentations (e.g. offers labels that can be referenced and things like "info"/"warning" boxes).

2021-10-08 09:13 UTC, vincentberenz commented on E5_documentation.md
> +- If you add a new file: in the content list, the orders of the page is alphabetical. Name your new markdown file based on the order into which it should appear in the content list.
@luator done !

2021-10-11 07:05 UTC, luator approved these changes

2021-10-11 07:05 UTC, luator commented on .gitignore
> +_templates/
What is the reason for ignoring them?  I think right now they are empty (except of a `.keep` file for git) but they are generally part of the documentation source files.

2021-10-11 07:44 UTC, vincentberenz commented on .gitignore
> +_templates/
I just assumed they were created by make, without looking much into it. I removed them from gitignore

2021-10-11 08:58 UTC, dtrb approved these changes
lgtm

2021-10-11 09:15 UTC, merged